// Shared inline styles for admin chrome. Co-located in JS so they can use the
// brand CSS variables without producing dozens of utility classes.
export const styles = {
  shell: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'var(--sb-navy)',
    color: 'var(--sb-cream)',
  },
  topbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 1.5rem',
    height: 56,
    background: 'var(--sb-navy-deep)',
    borderBottom: '0.5px solid rgba(196,132,58,0.25)',
    flexShrink: 0,
  },
  workspace: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  sidebar: {
    width: 280,
    background: 'var(--sb-navy-deep)',
    borderRight: '0.5px solid rgba(196,132,58,0.18)',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    overflow: 'hidden',
  },
  sidebarSection: { padding: '1rem 1rem 0.5rem' },
  sidebarLabel: {
    fontFamily: 'var(--sb-font-label)',
    fontSize: '0.62rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'var(--sb-gold)',
    marginBottom: '0.75rem',
    paddingBottom: '0.4rem',
    borderBottom: '0.5px solid rgba(196,132,58,0.18)',
  },
  pageItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 0.75rem',
    borderRadius: 'var(--sb-radius)',
    cursor: 'pointer',
    marginBottom: 2,
  },
  pageItemActive: { background: 'rgba(196,132,58,0.12)' },
  sectionList: { flex: 1, overflowY: 'auto', padding: '0 1rem 1rem' },
  secItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    padding: '0.5rem 0.65rem',
    borderRadius: 'var(--sb-radius)',
    cursor: 'pointer',
    marginBottom: 2,
    border: '0.5px solid transparent',
  },
  secItemActive: {
    background: 'rgba(196,132,58,0.1)',
    border: '0.5px solid rgba(196,132,58,0.25)',
  },
  addBtn: {
    width: '100%',
    padding: '0.55rem',
    background: 'rgba(196,132,58,0.08)',
    border: '0.5px dashed rgba(196,132,58,0.3)',
    borderRadius: 'var(--sb-radius)',
    color: 'var(--sb-gold)',
    fontSize: '0.72rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    fontFamily: 'var(--sb-font-body)',
    marginTop: '0.5rem',
  },
  editorPane: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRight: '0.5px solid rgba(196,132,58,0.18)',
  },
  editorHeader: {
    padding: '0.75rem 1.25rem',
    background: 'var(--sb-navy-deep)',
    borderBottom: '0.5px solid rgba(196,132,58,0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
  },
  editorBody: { flex: 1, overflowY: 'auto', padding: '1.25rem' },
  saveBar: {
    padding: '0.75rem 1.25rem',
    background: 'var(--sb-navy-deep)',
    borderTop: '0.5px solid rgba(196,132,58,0.18)',
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'center',
    flexShrink: 0,
  },
  previewPane: {
    width: '46%',
    minWidth: 420,
    background: 'var(--sb-ivory)',
    color: 'var(--sb-navy)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  previewHeader: {
    padding: '0.75rem 1.25rem',
    background: 'white',
    borderBottom: '0.5px solid var(--sb-taupe)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
  },
  card: {
    background: 'var(--sb-navy-deep)',
    border: '0.5px solid rgba(196,132,58,0.18)',
    borderRadius: 'var(--sb-radius)',
    padding: '1.25rem',
    marginBottom: '1rem',
  },
  cardTitle: {
    fontFamily: 'var(--sb-font-label)',
    fontSize: '0.7rem',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: 'var(--sb-gold)',
    marginBottom: '1rem',
    paddingBottom: '0.5rem',
    borderBottom: '0.5px solid rgba(196,132,58,0.18)',
  },
  fieldLabel: {
    fontFamily: 'var(--sb-font-label)',
    fontSize: '0.68rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: 'var(--sb-dusty)',
    marginBottom: '0.4rem',
    display: 'block',
  },
  fieldGroup: { marginBottom: '1.1rem' },
};
