"""Stamp a tailored application document (.docx) with accurate metadata and,
once a version is approved, its QR code.

python-docx writes a fixed placeholder (created/modified 2013-12-23) into
every file it generates, so packages built with it carry wrong dates. This
rewrites the core properties from real values and, with --qr-url, places
the approved version's QR code in the top-right of the page header.

Usage:
  pip install python-docx "qrcode[pil]"
  python scripts/stamp-application-package-docx.py in.docx out.docx \
      --authors "Charles Phillipe; Betsy Salter" \
      --created 2026-09-30T13:00:01Z \
      [--modified 2026-10-02T03:00:00Z]     # default: now
      [--last-modified-by "Betsy Salter"]   # the approver, once approved
      [--qr-url https://saltbasin.net/r/<slug>]

Get --qr-url from My Resume → Resume Output History after "Approve for QR".
"""
import argparse
import io
from datetime import datetime, timezone

import docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.opc.constants import RELATIONSHIP_TYPE as RT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


def parse_ts(value):
    return datetime.fromisoformat(value.replace('Z', '+00:00')).astimezone(timezone.utc).replace(tzinfo=None)


def add_qr_to_header(document, url):
    import qrcode

    img = qrcode.make(url, border=1, error_correction=qrcode.constants.ERROR_CORRECT_M)
    buf = io.BytesIO()
    img.save(buf, format='PNG')
    section = document.sections[0]
    section.different_first_page_header_footer = False
    header = section.header
    para = header.paragraphs[0] if header.paragraphs and not header.paragraphs[0].text.strip() else header.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    buf.seek(0)
    # Files are mostly read on screen, so the QR and its caption are also
    # clickable links to the same slug.
    rel_id = header.part.relate_to(url, RT.HYPERLINK, is_external=True)
    inline = para.add_run().add_picture(buf, width=Inches(0.7))._inline
    link = OxmlElement('a:hlinkClick')
    link.set(qn('r:id'), rel_id)
    inline.docPr.append(link)

    caption = header.add_paragraph()
    caption.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    hyperlink = OxmlElement('w:hyperlink')
    hyperlink.set(qn('r:id'), rel_id)
    run = caption.add_run('Scan or click for current version')
    run.font.size = Pt(6)
    run.font.color.rgb = RGBColor(0x4A, 0x7C, 0x8E)
    caption._p.remove(run._r)
    hyperlink.append(run._r)
    caption._p.append(hyperlink)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('src')
    ap.add_argument('dest')
    ap.add_argument('--authors', required=True)
    ap.add_argument('--created', required=True)
    ap.add_argument('--modified')
    ap.add_argument('--last-modified-by')
    ap.add_argument('--qr-url')
    args = ap.parse_args()

    document = docx.Document(args.src)
    props = document.core_properties
    authors = '; '.join(a.strip() for a in args.authors.split(';') if a.strip())
    props.author = authors
    props.last_modified_by = args.last_modified_by or authors.split('; ')[-1]
    props.created = parse_ts(args.created)
    props.modified = parse_ts(args.modified) if args.modified else datetime.now(timezone.utc).replace(tzinfo=None)
    if props.comments == 'generated by python-docx':
        props.comments = ''
    if args.qr_url:
        add_qr_to_header(document, args.qr_url)
    document.save(args.dest)
    print(f'{args.dest}: author={props.author!r} created={props.created} modified={props.modified} lastModifiedBy={props.last_modified_by!r}{" +QR" if args.qr_url else ""}')


if __name__ == '__main__':
    main()
