export const LONETREE_PROPOSAL_NARRATIVE = {
  headerLabel: 'Executive proposal · Prepared exclusively for LoneTree Capital',
  breadcrumbLabel: 'Proposal Narrative',
  completeDownload: { label: 'Download Complete Proposal and Notes', url: '/api/lonetree-mvp/complete-proposal-package' },
  archiveDownload: { label: 'Archived: Prospect Experience V5', url: '/api/lonetree-mvp/prospect-package' },
  playback: { intervalMs: 18000, startAutomatically: false },
  visual: { highlightGlow: 'rgba(74,124,142,.32)', motionEnabled: true, revealIntervalMs: 1100 },
  cover: {
    eyebrow: 'Phase 1 diagnostic and value proof proposal',
    title: "Let's take your under-utilized data to the next level, shall we?",
    body: 'A PE executive proposal for finding operational timing and opportunity, validating revenue leakage, translating evidence into Value Recovery Initiatives, and preserving defensible outcomes from sponsor thesis through PortCo execution.',
  },
  sections: [
    { id: 'investment-case', label: 'Investment Case', eyebrow: '01 · Investment Case', title: 'Prove the thesis. Build the evidence for what comes next.', narrative: 'The opportunity is larger than a CRM, reporting, or portfolio-monitoring decision. It is the ability to preserve the meaning and evidence behind business outcomes from sourcing through exit.', heading: 'Timing and Opportunity are found operationally before technical.', highlightIndex: 3, cards: [{ marker: '01', title: 'Fragmented pipeline', body: 'Excel, Salesforce, financing, and relationship data do not resolve to one time-aware priority view.' }, { marker: '02', title: 'Manual reporting', body: 'Quarterly packages and mappings require repeated manipulation and reconciliation.' }, { marker: '03', title: 'Definition drift', body: 'ARR, EBITDA, pricing, and margin claims change meaning across systems and periods.' }, { marker: '04', title: 'Exit reconstruction', body: 'The value-creation story is rebuilt during diligence instead of accumulated through the hold.' }], banner: 'The decision: validate the evidence model on LoneTree’s history, then scale only where economics and decision value are proven.' },
    { id: 'value-creation', label: 'Value Creation', eyebrow: '02 · Value Creation', title: 'From operating signals to defensible value.', narrative: 'Salt Basin turns the investment thesis into a persistent, testable evidence object so the firm can prioritize, underwrite, measure, attribute, and prove with the same governed language.', rail: [{ marker: '01', title: 'Believe', body: 'Versioned claim' }, { marker: '02', title: 'Define', body: 'Metric + rules' }, { marker: '03', title: 'Observe', body: 'Source events' }, { marker: '04', title: 'Classify', body: 'Movement drivers' }, { marker: '05', title: 'Attribute', body: 'Confidence' }, { marker: '06', title: 'Prove', body: 'Reconciled outcome' }], panels: [{ eyebrow: 'For the firm', title: 'Sponsor operating layer', items: ['Dynamic account and relationship prioritization', 'Financing, debt, covenant, and liquidity visibility', 'Quarterly claim maturity and attribution', 'LP, lender, and buyer diligence proof'] }, { eyebrow: 'For PortCos', title: 'Lead-to-cash operating partner', dark: true, items: ['Protect revenue', 'Improve cash conversion', 'Reduce reporting friction', 'Preserve outcome evidence'] }] },
    { id: 'phase-one', label: 'Phase 1', eyebrow: '03 · Phase 1 Partnership', title: 'Prove the method on LoneTree’s evidence—then expand where it works.', narrative: 'A bounded diagnostic of historical fund thesis and selected PortCo claims, with success measured by evidence rather than software adoption.', highlightIndex: 0, cards: [{ marker: 'A', title: 'Thesis-to-exit map', body: 'Belief → measure → proof.' }, { marker: 'B', title: 'Truth-cost baseline', body: 'Effort, breaks, and gaps.' }, { marker: 'C', title: 'Metric register', body: 'ARR, NRR, margin, and cash.' }, { marker: 'D', title: 'Breakpoint heatmap', body: 'Lineage and control failures.' }], panels: [{ eyebrow: 'Additional outputs', title: 'Decision-ready plan', items: ['100-day opportunity map', 'Minimum-definition blueprint', 'Evidence confidence assessment', 'Prioritized Value Recovery Initiatives'] }, { eyebrow: 'Engagement lead', title: 'Martha (Betsy) Salter', dark: true, body: '10+ years spanning private equity, consulting, SaaS, healthcare technology, manufacturing, and enterprise software—connecting sponsor-level thesis to PortCo lead-to-cash execution.' }] },
    { id: 'diagnostic-proof', label: 'Diagnostic + Proof', eyebrow: '04 · Diagnostic + Value Proof', title: 'Diagnose the leakage. Prove the value. Fund what works.', narrative: 'Phase 1 converts workbook risk hypotheses into company-specific findings. A separately scoped value-proof layer can quantify recovered revenue, cash, margin, cycle time, and evidence quality for an additional fee.', highlightIndex: 3, cards: [{ marker: '01', title: 'Hypothesis', body: 'Translate scenarios into testable claims.' }, { marker: '02', title: 'Diagnostic', body: 'Trace process, data, controls, and exceptions.' }, { marker: '03', title: 'Validation', body: 'Reconcile contracts, billing, cash, and GL.' }, { marker: '04', title: 'Value proof', body: 'Baseline, implement, measure, and substantiate recovery.' }], panels: [{ eyebrow: 'Included', title: 'Diagnostic outputs', items: ['Claim register', 'Process and system map', 'Control and exception heatmap', 'Quantified findings with confidence', 'Value Recovery Initiatives roadmap'] }, { eyebrow: 'Additional fee', title: 'Realized-value proof', dark: true, body: 'Establish the baseline, support selected recovery initiatives, and validate realized impact against authoritative source events.' }] },
    { id: 'tactical-design', label: 'Tactical Design', eyebrow: '05 · Tactical Diagnostic Design', title: 'Every claim resolves to an authoritative event trail.', narrative: 'Preferred lookback is 24–36 months; minimum is 12 months plus the current period, using the longest reliable history available.', columns: ['Claim / test', 'Source events', 'Likely system', 'Time scope', 'Proof standard'], rows: [['Price / discount', 'Terms, amendments, price books, invoices', 'CLM, CPQ, billing', '24–36 months', 'Contracted vs billed rate'], ['Usage mismatch', 'Usage events, tiers, credits', 'Product, warehouse, billing', '12–24 months', 'Rated usage vs invoice and cash'], ['Amendment divergence', 'Document history, CRM changes, audit log', 'CLM, CRM, billing', 'Full contract history', 'Signed change vs configuration'], ['Unbilled revenue', 'Orders, fulfillment, invoices, AR, cash', 'ERP, product, billing, bank', '12–24 months', 'Earned vs billed / collected'], ['Revenue / margin', 'Invoices, credits, rev rec, JE, COA', 'Billing, rev rec, ERP / GL', '24–36 months', 'Event → subledger → GL → KPI']], banner: 'Standard data request: customer master · quote/order · contracts/amendments · entitlements · usage/fulfillment · billing configuration · invoices/credits · AR/cash · revenue schedules · JE/COA · product/price master · audit logs · definitions · exception files.' },
    { id: 'delivery-options', label: 'Delivery Options', eyebrow: '06 · Delivery Options', title: 'Choose the model that creates the strongest evidence.', narrative: 'Both options begin with the same prerequisite data request. Final fixed fee depends on scope, data complexity, duration, and number of company participants.', panels: [{ eyebrow: 'Option 1 · Multi-day bootcamp', title: 'Best portfolio learning per session', body: 'Preferred: sponsor + bank/capital partner + 1–3 PortCos for maximum value and a group fixed fee.', items: ['Data delivered in advance', 'Planning session for findings, attendees, agenda, and schedule', 'End-to-end lead-to-cash walkthrough', 'Pain points, exceptions, risk, and controls', 'Cross-company Value Recovery Initiatives'] }, { eyebrow: 'Option 2 · 10-day diagnostic', title: 'Deeper company-specific validation', dark: true, body: 'Base scope: sponsor + one PortCo. Days 1–5 interview end-to-end processes while synthesizing data and preliminary findings. Days 6–10 refine deliverables, validate findings, quantify opportunity, and finalize the roadmap.' }], banner: 'Commercial structure: Engagement fixed fee dependent on scope and number of company participants.' },
  ],
};
