// Interface-parity map (2026-10-09). A config registry - no table - listing every capability in the governed
// route files with the three ways it must be usable:
//
//   ui   - the World Shell path a person clicks (desktop and a 390px phone), or null when there is none yet
//   api  - the API route(s) the UI calls (and the MCP tool's handler shares the server function behind them)
//   mcp  - the MCP tool name(s) in server/lib/mcpToolRegistry.js, or null when there is none yet
//
// A missing ui/mcp is recorded as a GAP and shown highlighted on World Shell -> Capabilities (admin). A path
// that is deliberately not offered in an interface carries an `exclusion` with the reason instead
// (uiExclusion / mcpExclusion) - never a silent blank. `node scripts/check-interface-parity.mjs` verifies the
// registry against the code (routes exist, tools exist, every governed route is listed, shipped tools were not
// removed) and `--strict` fails while any gap remains. APPEND-ONLY in spirit like the block REGISTRY: a
// capability is changed by filling in its gap, not by deleting its row.
import { MCP_TOOL_NAMES } from './mcpToolRegistry.js';

/** Route files under parity governance: file -> mount path (kept in step with server/index.js by the check). */
export const GOVERNED_ROUTE_FILES = Object.freeze({
  'server/routes/careerPlacementAgents.js': '/api/career-agents',
  'server/routes/resumeOutputs.js': '/api/resume-outputs',
  'server/routes/coverLetters.js': '/api/cover-letters',
  'server/routes/platformAccess.js': '/api/platform',
  'server/routes/careerMaster.js': '/api/career',
  'server/routes/sharedOutputs.js': '/api/shared-outputs',
  'server/routes/releaseIntelligence.js': '/api/release-intelligence',
  'server/routes/sessionMapping.js': '/api/session-mapping',
  'server/routes/renderBindings.js': '/api/render-bindings',
  'server/routes/flowStudio.js': '/api/flow-studio',
  'server/routes/careerReconciliation.js': '/api/career-reconciliation',
  'server/routes/careerBound.js': '/api/career-bound',
  'server/routes/outputTemplates.js': '/api/output-templates',
  'server/routes/agentRunner.js': '/api/agent-runner',
  'server/routes/releaseCut.js': '/api/release-cut',
  'server/routes/releaseTracker.js': '/api/release-tracker',
  'server/routes/dataModelMap.js': '/api/data-model',
  'server/routes/productionSmoke.js': '/api/production-smoke',
});

/** For files governed only in part: file -> pattern a route (`METHOD /full/path`) must match to be governed.
 *  Empty: server/routes/careerMaster.js is governed in full (every route has a row below). */
export const GOVERNED_ROUTE_FILTERS = Object.freeze({});

const CPA = '/api/career-agents';
const RO = '/api/resume-outputs';
const CL = '/api/cover-letters';
const CM = '/api/career';
const CR = '/api/career-reconciliation';
const CB = '/api/career-bound';
const OT = '/api/output-templates';
const RBA = '/api/render-bindings';
const DMA = '/api/data-model';
const FSA = '/api/flow-studio';
const RR = `World Shell > Journeys > Career Master > Resume rollups`;
const WS = 'World Shell';
const PROF = `${WS} > Journeys > Career Master > Proficiency & Rollups > 3 · Rules & why`;
const OPP = `${WS} > Journeys > Career Placement Agents > (select an opportunity)`;
const RESUME = `${WS} > Journeys > My Resume`;

export const CAPABILITIES = Object.freeze([
  // ── Career Master and tracked opportunities ───────────────────────────────
  { key: 'career-master-read', title: 'Read the Career Master', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: ['GET /api/career/master'], mcp: ['career_master_read'] },
  { key: 'agent-hub-read', title: 'See the agent hub (agents and counts)', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents`, api: [`GET ${CPA}/agent-hub`], mcp: ['career_agent_hub_read'] },
  { key: 'opportunities-list', title: 'List tracked opportunities', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents`, api: [`GET ${CPA}/opportunities`], mcp: ['career_opportunities_list'] },
  { key: 'opportunity-create', title: 'Track a new opportunity', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents > Track`, api: [`POST ${CPA}/opportunities`], mcp: ['career_opportunity_create'] },
  { key: 'opportunity-open', title: 'Open one tracked opportunity', group: 'Career opportunities', ui: OPP, api: [`GET ${CPA}/opportunities/:id`], mcp: ['career_opportunity_open'] },
  { key: 'opportunity-details', title: 'Fill in opportunity details', group: 'Career opportunities', ui: `${OPP} > Save details`, api: [`PATCH ${CPA}/opportunities/:id`], mcp: ['career_opportunity_update_details'] },
  { key: 'career-scoring-preferences', title: 'Adjust my opportunity scoring weights (read, save, reset)', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents > Scoring Weights (also Classic Tools > Career Placement Agents > Opportunity Scoring Weights > Adjust)`, api: [`GET ${CPA}/scoring-preferences`, `PUT ${CPA}/scoring-preferences`, `DELETE ${CPA}/scoring-preferences`], mcp: ['career_scoring_preferences_read', 'career_scoring_preferences_save', 'career_scoring_preferences_reset'] },
  { key: 'opportunity-scores', title: 'Record dimension scores', group: 'Career opportunities', ui: `${OPP}`, api: [`POST ${CPA}/opportunities/:id/scores`], mcp: ['career_opportunity_scores_record'] },
  { key: 'opportunity-approve', title: 'Approve an opportunity to pursue', group: 'Career opportunities', ui: OPP, api: [`POST ${CPA}/opportunities/:id/approve`], mcp: ['career_opportunity_approve'] },
  { key: 'opportunity-advance-stage', title: 'Advance an opportunity stage', group: 'Career opportunities', ui: OPP, api: [`POST ${CPA}/opportunities/:id/advance-stage`], mcp: ['career_opportunity_advance_stage'] },
  { key: 'pipeline-import', title: 'Import a pipeline workbook', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents`, api: [`POST ${CPA}/import`], mcp: null, mcpExclusion: 'File upload; an agent creates opportunities one at a time with career_opportunity_create.' },
  { key: 'research-run', title: 'Run career research', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents`, api: [`POST ${CPA}/research`], mcp: ['career_research_run'] },
  { key: 'pipeline-verify', title: 'Run the qualification gates now', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents`, api: [`POST ${CPA}/verify-pipeline`, `GET ${CPA}/verification-current`], mcp: ['career_pipeline_verify', 'career_verification_current_read'] },
  { key: 'verification-current-edit', title: 'Edit the qualification gate definition (admin)', group: 'Career opportunities', ui: `${WS} > Journeys > Qualification Rules > Save qualification rule (administrators)`, api: [`PUT ${CPA}/verification-current`], mcp: ['career_verification_current_save'] },
  { key: 'agent-schedule', title: 'View and change the agent schedule', group: 'Career opportunities', ui: `${WS} > Journeys > Career Placement Agents > Schedules`, api: [`GET ${CPA}/schedule`, `POST ${CPA}/schedule`], mcp: ['career_agent_schedule_read', 'career_agent_schedule_save'] },
  { key: 'outreach', title: 'Outreach: start, research contacts, draft, save, merge outcome', group: 'Career opportunities', ui: `${OPP} > Outreach & Hiring Manager Research`, api: [`GET ${CPA}/opportunities/:id/outreach`, `POST ${CPA}/opportunities/:id/outreach/start`, `POST ${CPA}/opportunities/:id/outreach/research-contacts`, `POST ${CPA}/opportunities/:id/outreach/draft-message`, `POST ${CPA}/opportunities/:id/outreach/messages`, `POST ${CPA}/outreach/:id/merge-outcome`], mcp: ['career_outreach_read', 'career_outreach_start', 'career_outreach_research_contacts', 'career_outreach_draft_message', 'career_outreach_message_save', 'career_outreach_merge_outcome'] },

  // ── Application outputs ───────────────────────────────────────────────────
  { key: 'application-outputs-list', title: 'List the outputs linked to an opportunity (with provenance)', group: 'Application outputs', ui: `${OPP} > APPLICATION OUTPUTS`, api: [`GET ${CPA}/opportunities/:id/outputs`], mcp: ['application_outputs_list'] },
  { key: 'application-output-link', title: 'Link or unlink an existing output', group: 'Application outputs', ui: `${OPP} > APPLICATION OUTPUTS > Link an Existing Output / Unlink`, api: [`GET ${CPA}/unlinked-outputs`, `POST ${CPA}/opportunities/:id/outputs/:outputId/link`, `DELETE ${CPA}/opportunities/:id/outputs/:outputId/link`], mcp: ['application_outputs_unlinked_list', 'application_output_link', 'application_output_unlink'] },
  { key: 'application-output-open', title: 'Open an output\'s document content', group: 'Application outputs', ui: `${OPP} > APPLICATION OUTPUTS > Edit draft`, api: [`GET ${CPA}/resume-outputs/:id/content`], mcp: ['application_output_open'] },
  { key: 'application-output-new-draft', title: 'Save a new draft version', group: 'Application outputs', ui: `${OPP} > APPLICATION OUTPUTS > Edit draft > Save`, api: [`POST ${CPA}/resume-outputs/:id/versions`], mcp: ['application_output_new_draft_version'] },
  { key: 'application-output-approve-qr', title: 'Approve an output for its QR link', group: 'Application outputs', ui: `${OPP} > APPLICATION OUTPUTS > Approve for QR`, api: [`POST ${RO}/:id/share`], mcp: ['application_output_approve_for_qr'] },
  { key: 'application-output-revoke-qr', title: 'Revoke a QR link', group: 'Application outputs', ui: `${RESUME}`, api: [`DELETE ${RO}/:id/share`], mcp: ['application_output_revoke_qr'] },
  { key: 'application-output-qr-image', title: 'Download the QR image', group: 'Application outputs', ui: `${RESUME}`, api: [`GET ${RO}/:id/qr.:format(svg|png)`], mcp: null, mcpExclusion: 'Binary image; the approve tool returns the shareable URL.' },
  { key: 'shared-output-resolve', title: 'Open an approved output by its private QR link', group: 'Application outputs', ui: 'Scan the QR code or open the /r/ link (public page)', api: ['GET /api/shared-outputs/:token'], mcp: ['shared_output_resolve'] },
  { key: 'application-output-docx', title: 'Download the stamped .docx (slug QR, real dates)', group: 'Application outputs', ui: `${RESUME} > Download .docx`, api: [`GET ${RO}/:id/download.docx`], mcp: null, mcpExclusion: 'Binary file; the approve tool returns the shareable URL.' },
  { key: 'application-package-import', title: 'Import an application package', group: 'Application outputs', ui: `${RESUME} > Import an application package`, api: [`POST ${RO}/import-package`], mcp: ['application_package_import'] },
  { key: 'resume-outputs-list', title: 'List my resume outputs', group: 'Resume outputs', ui: `${RESUME}`, api: [`GET ${RO}`], mcp: ['resume_outputs_list'] },
  { key: 'resume-output-generate', title: 'Generate a resume output from the Career Master', group: 'Resume outputs', ui: `${RESUME}`, api: [`POST ${RO}`], mcp: ['resume_output_generate'] },
  { key: 'resume-output-staleness', title: 'Check whether an output is stale', group: 'Resume outputs', ui: `${RESUME} > Check freshness`, api: [`GET ${RO}/:id/staleness`], mcp: ['resume_output_staleness'] },
  { key: 'resume-output-versions', title: 'Version history of an output', group: 'Resume outputs', ui: `${RESUME} > Version history`, api: [`GET ${RO}/:id/versions`], mcp: ['output_versions_list', 'output_version_read', 'output_versions_compare', 'resume_output_versions'] },
  { key: 'resume-output-status', title: 'Approve or publish an output (status)', group: 'Resume outputs', ui: `${RESUME}`, api: [`PATCH ${RO}/:id/status`], mcp: ['resume_output_status_set'] },
  { key: 'finalization-check', title: 'Check what blocks finalizing', group: 'Resume outputs', ui: `${RESUME}`, api: [`GET ${RO}/finalization-check`], mcp: ['finalization_check'] },
  { key: 'opportunity-resumes', title: 'Generate, approve and list resumes for an opportunity', group: 'Resume outputs', ui: `${OPP}`, api: [`POST ${CPA}/opportunities/:id/generate-resume`, `POST ${CPA}/opportunities/:id/resume-outputs`, `GET ${CPA}/opportunities/:id/resume-outputs`, `POST ${CPA}/generate-resume-queue`, `POST ${CPA}/auto-queue-outputs`], mcp: ['career_resume_generate', 'career_resume_output_save', 'career_opportunity_resumes_list', 'career_resume_queue_generate', 'career_auto_queue_outputs'] },
  { key: 'opportunity-import-output', title: 'Import a document into an opportunity', group: 'Resume outputs', ui: `${OPP} > Or Import an Existing Document`, api: [`POST ${CPA}/opportunities/:id/import-output`], mcp: null, mcpExclusion: 'File upload; an agent saves content with application_output_new_draft_version.' },
  { key: 'resume-output-view-download', title: 'View, download PDF, ZIP or email outputs', group: 'Resume outputs', ui: `${RESUME}`, api: [`GET ${CPA}/resume-outputs/:id/view`, `GET ${CPA}/resume-outputs/:id/download.pdf`, `POST ${CPA}/resume-outputs/export-zip`, `POST ${CPA}/resume-outputs/email`], mcp: ['career_output_view', 'career_outputs_email'] },
  { key: 'opportunity-cover-letter-legacy', title: 'Generate and approve an agent cover letter (legacy path)', group: 'Cover letters', ui: `${OPP}`, api: [`POST ${CPA}/opportunities/:id/generate-cover-letter`, `POST ${CPA}/opportunities/:id/cover-letter-outputs`], mcp: ['career_cover_letter_generate', 'career_cover_letter_output_save'] },

  // ── Career-bound outputs, package reconciliation, per-preset overrides ────
  { key: 'reconciliation-tasks', title: 'See and resolve the Career Master reconciliation queue', group: 'Career-bound outputs', ui: `${WS} > Journeys > Career Master > Review queue`, api: [`GET ${CR}/tasks`, `POST ${CR}/tasks/:id/resolve`, `POST ${CR}/tasks/:id/retry-sync`], mcp: ['career_reconciliation_tasks_list', 'career_reconciliation_task_resolve', 'career_reconciliation_task_retry_sync'] },
  { key: 'reconciliation-package-source', title: 'Import a package as a reconciliation source', group: 'Career-bound outputs', ui: `${RESUME} > Import an application package`, api: [`POST ${CR}/package-sources`], mcp: ['career_reconciliation_package_import'] },
  { key: 'career-bound-bullets', title: 'Add, edit or delete a Career Master bullet', group: 'Career-bound outputs', ui: `${RESUME} > Career-bound output editor > Bullets`, api: [`GET ${CB}/jobs`, `POST ${CB}/jobs/:jobId/bullets`, `PATCH ${CB}/jobs/:jobId/bullets/:bulletId`, `DELETE ${CB}/jobs/:jobId/bullets/:bulletId`], mcp: ['career_bound_jobs_list', 'career_bound_bullet_add_to_master', 'career_bound_bullet_update', 'career_bound_bullet_delete'] },
  { key: 'career-bound-convert', title: 'Convert a package resume to career-bound', group: 'Career-bound outputs', ui: `${RESUME} > Convert to career-bound`, api: [`GET ${CB}/convertible`, `GET ${CB}/convert/:projectionId/preview`, `POST ${CB}/convert/:projectionId`, `GET ${CB}/review-count`], mcp: ['career_bound_convertible_list', 'career_bound_convert_preview', 'career_bound_convert', 'career_bound_review_count'] },
  { key: 'career-bound-output', title: 'Create, open, preview and edit a career-bound output (field overrides, output-only bullets)', group: 'Career-bound outputs', ui: `${RESUME} > Career-bound output editor`, api: [`POST ${CB}/outputs`, `GET ${CB}/outputs/:id`, `POST ${CB}/outputs/:id/preview`, `PUT ${CB}/outputs/:id`], mcp: ['career_bound_output_create', 'career_bound_output_open', 'career_bound_output_preview', 'career_bound_output_save'] },
  { key: 'output-template-presets', title: 'Output presets and per-preset Career Master overrides', group: 'Career-bound outputs', ui: `${RESUME} > Output templates`, api: [`GET ${OT}`, `GET ${OT}/primary`, `GET ${OT}/portfolio`, `GET ${OT}/:id/public`, `POST ${OT}`, `PUT ${OT}/:id`, `DELETE ${OT}/:id`], mcp: ['output_templates_list', 'output_templates_primary_read', 'output_templates_portfolio_read', 'output_template_public_read', 'output_template_create', 'output_template_update', 'output_template_delete'] },

  // ── Cover letters ─────────────────────────────────────────────────────────
  { key: 'cover-letter-settings', title: 'Cover-letter settings', group: 'Cover letters', ui: `${RESUME} > Cover-letter settings`, api: [`GET ${CL}/settings`, `PUT ${CL}/settings`], mcp: ['cover_letter_settings_read', 'cover_letter_settings_save'] },
  { key: 'cover-letter-packages', title: 'Packages per opportunity: list, job text, draft letter, assemble', group: 'Cover letters', ui: `${RESUME} > Application packages`, api: [`GET ${CL}/opportunities`, `PUT ${CL}/opportunities/:id/job-rec`, `POST ${CL}/opportunities/:id/cover-letter`, `POST ${CL}/opportunities/:id/package`, `POST ${CL}/packages/assemble`], mcp: ['cover_letter_opportunities_list', 'cover_letter_job_rec_save', 'cover_letter_generate', 'cover_letter_package_build', 'cover_letter_packages_list', 'cover_letter_job_text_set', 'cover_letter_draft_for_opportunity', 'cover_letter_packages_assemble'] },
  { key: 'cover-letter-add-resume', title: 'Add a resume to a package from a file', group: 'Cover letters', ui: `${RESUME} > Application packages`, api: [`POST ${CPA}/opportunities/:id/import-output`], mcp: null, mcpExclusion: 'File upload; an agent saves content with application_output_new_draft_version.' },
  { key: 'cover-letter-open', title: 'Open a cover letter', group: 'Cover letters', ui: `${RESUME} > Application packages (Open)`, api: [`GET ${CL}/letters/:id`], mcp: ['cover_letter_open'] },
  { key: 'cover-letter-agent-turn', title: 'Ask the cover-letter agent for an edit', group: 'Cover letters', ui: `${RESUME} > Application packages (Open)`, api: [`POST ${CL}/letters/:id/turns`], mcp: ['cover_letter_agent_turn'] },
  { key: 'cover-letter-turns', title: 'Read the agent conversation and metrics', group: 'Cover letters', ui: `${RESUME} > Application packages (Open)`, api: [`GET ${CL}/letters/:id/turns`, `GET ${CL}/metrics`], mcp: ['cover_letter_turns_list', 'cover_letter_turns_read', 'cover_letter_metrics_read'] },
  { key: 'cover-letter-turn-decide', title: 'Accept or reject a proposed edit', group: 'Cover letters', ui: `${RESUME} > Application packages (Open) > Accept / Reject`, api: [`POST ${CL}/turns/:id/accept`, `POST ${CL}/turns/:id/reject`], mcp: null, mcpExclusion: 'Applying a proposal is a human decision made in the website, by design.' },

  // ── Career Master: resume rollups and definitions ─────────────────────────
  { key: 'resume-rollups-read', title: 'Read computed resume rollups (KPI tiles, industry buckets, category groups)', group: 'Resume rollups', ui: `${WS} > Journeys > Career Master > Resume rollups`, api: [`GET ${CM}/resume-rollups`], mcp: ['resume_rollups_read'] },
  { key: 'resume-rollups-preview', title: 'Live preview of unsaved rollup definitions', group: 'Resume rollups', ui: `${WS} > Journeys > Career Master > Resume rollups`, api: [`POST ${CM}/resume-rollups/preview`], mcp: ['resume_rollup_preview'] },
  { key: 'career-atom-rollups-read', title: 'Read Career Atom rollups', group: 'Resume rollups', ui: `${WS} > Journeys > Career Master > Resume rollups`, api: [`GET ${CM}/atom-rollups`], mcp: ['career_atom_rollups_read'] },
  { key: 'experience-definitions-read', title: 'List experience and rollup definitions', group: 'Resume rollups', ui: `${WS} > Journeys > Career Master > Resume rollups`, api: [`GET ${CM}/experience-definitions`], mcp: ['career_experience_definitions_read'] },
  { key: 'experience-definition-save', title: 'Save or reorder a definition (tile, bucket, group, Career Atom card)', group: 'Resume rollups', ui: `${RR} > Save / up / down`, api: [`PUT ${CM}/experience-definitions/:type/:key`], mcp: ['career_experience_definition_save'] },
  { key: 'experience-definition-delete', title: 'Remove a definition', group: 'Resume rollups', ui: `${RR} > Remove`, api: [`DELETE ${CM}/experience-definitions/:type/:key`], mcp: ['career_experience_definition_delete'] },
  { key: 'career-proficiency-read', title: 'Read resolved proficiency and rollup policy previews', group: 'Resume rollups', ui: `${WS} > Journeys > Career Master > Proficiency`, api: [`GET ${CM}/rollup-preview/:key`, `GET ${CM}/rollups`], mcp: ['career_rollups_read', 'career_rollup_preview_read'] },

  // ── Career Master: other routes (listed so the file can be governed; MCP gaps are recorded, not hidden) ──
  { key: 'career-public-reads', title: 'Public/shared Career Master reads (public rollup, catalogs)', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: [`GET ${CM}/public-rollup/:slug/:displayKey`, `GET ${CM}/catalogs`], mcp: ['career_catalogs_read', 'career_public_rollup_read'] },
  { key: 'career-consent', title: 'Career Portfolio terms (status and accept)', group: 'Career Master', ui: `${WS} (first sign-in step)`, api: [`GET ${CM}/consent-status`, `POST ${CM}/consent`], mcp: null, mcpExclusion: 'Accepting terms is a personal decision made in the website; MCP calls are refused until it is done.' },
  { key: 'career-intake', title: 'Intake documents and runs (upload, LinkedIn pull, run, semantic import, analysis)', group: 'Career Master', ui: `${WS} > Journeys > Career Master > Manual Intake`, api: [`GET ${CM}/intake-documents`, `POST ${CM}/intake-documents`, `POST ${CM}/intake-documents/linkedin-pull`, `GET ${CM}/intake-runs`, `POST ${CM}/intake-runs`, `POST ${CM}/intake-runs/:id/run`, `GET ${CM}/semantic-template`, `POST ${CM}/semantic-import`, `POST ${CM}/resume-analysis`], mcp: ['career_intake_documents_list', 'career_intake_linkedin_pull', 'career_intake_runs_list', 'career_intake_run_create', 'career_intake_run_execute', 'career_semantic_template_read'] },
  { key: 'career-mappings', title: 'Field mappings (classify, lineage, commit) and bounded agent action', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: [`POST ${CM}/mappings/classify`, `GET ${CM}/mappings/lineage`, `POST ${CM}/mappings/commit`, `POST ${CM}/bounded-agent/action`], mcp: ['career_mappings_classify', 'career_mappings_lineage', 'career_mappings_commit', 'career_bounded_agent_action'] },
  { key: 'career-master-records', title: 'Create, edit and delete Career Master records (jobs, skills, tools, engagements, domains, certifications, deals, meta options)', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: ['jobs', 'skills', 'tools', 'engagements', 'domains', 'certifications', 'deals', 'meta-options'].flatMap((r) => [`GET ${CM}/${r}`, `POST ${CM}/${r}`, `PATCH ${CM}/${r}/:id`, `DELETE ${CM}/${r}/:id`]), mcp: ['career_record_list', 'career_record_create', 'career_record_update', 'career_record_delete'] },
  { key: 'career-admin-utilities', title: 'Site metadata sync', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: [`POST ${CM}/sync-site-metadata`], mcp: ['career_site_metadata_sync'] },
  { key: 'career-seed-definitions', title: 'Seed Career Master definitions', group: 'Career Master', ui: `${WS} > Journeys > Career Master`, api: [`POST ${CM}/seed`], mcp: null, mcpExclusion: 'One-time maintenance seed run by the platform owner from the website; pending owner confirmation (see Fix notes round 3).' },
  // ── Proficiency rules, technology categories and the live QR page ─────────
  { key: 'proficiency-rules-read', title: 'Read proficiency rules and resolved levels', group: 'Proficiency rules', ui: PROF, api: [`GET ${CM}/proficiency`, `GET ${CM}/experience-definitions`], mcp: ['proficiency_rules_read'] },
  { key: 'proficiency-override', title: 'Override or clear one proficiency level', group: 'Proficiency rules', ui: PROF, api: [`GET ${CM}/proficiency-assertions`, `PUT ${CM}/proficiency-assertions/:entityType/:entityId/:periodKey`, `DELETE ${CM}/proficiency-assertions/:entityType/:entityId/:periodKey`], mcp: ['proficiency_override_set', 'proficiency_override_clear', 'career_proficiency_override_save', 'career_proficiency_override_clear'] },
  { key: 'technology-category', title: 'Set a technology\'s proficiency category', group: 'Proficiency rules', ui: PROF, api: [`PATCH ${CM}/tools/:id`], mcp: ['technology_category_set'] },
  { key: 'proficiency-formula', title: 'Save, select or delete a proficiency formula and certification bonus', group: 'Proficiency rules', ui: PROF, api: [`PUT ${CM}/experience-definitions/:type/:key`], mcp: ['proficiency_formula_save', 'proficiency_formula_select', 'certification_mapping_save'] },
  { key: 'proficiency-definition-delete', title: 'Delete a formula or certification bonus', group: 'Proficiency rules', ui: PROF, api: [`DELETE ${CM}/experience-definitions/:type/:key`], mcp: ['career_experience_definition_delete'] },
  { key: 'shared-output-live', title: 'Open the live QR page (and its PDF)', group: 'Application outputs', ui: `${WS} > Journeys > My Resume (QR link opens /r/:token)`, api: ['GET /api/shared-outputs/:token'], mcp: ['shared_output_live_read'] },
  { key: 'shared-output-pdf', title: 'Download the PDF from the live QR page', group: 'Application outputs', ui: `${WS} > Journeys > My Resume (QR link opens /r/:token)`, api: ['GET /api/shared-outputs/:token/download.pdf'], mcp: null, mcpExclusion: 'Binary document; shared_output_live_read returns the same content as data.' },

  // ── Release loop (admin) ──────────────────────────────────────────────────
  { key: 'release-loop-definition', title: 'Read and edit the release loop definition (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Definition`, api: ['GET /api/release-loop/definition', 'PUT /api/release-loop/definition', 'DELETE /api/release-loop/definition'], mcp: ['release_loop_get_definition', 'release_loop_save_definition'] },
  { key: 'release-loop-runs', title: 'List, start, read and move release loop runs (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Runs`, api: ['GET /api/release-loop/runs', 'POST /api/release-loop/runs', 'GET /api/release-loop/runs/:id', 'POST /api/release-loop/runs/:id/transition'], mcp: ['release_loop_list_runs', 'release_loop_start_run', 'release_loop_get_run', 'release_loop_transition_run'] },
  { key: 'release-loop-validation', title: 'Record rounds and live steps (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Runs`, api: ['POST /api/release-loop/runs/:id/rounds', 'POST /api/release-loop/runs/:id/steps'], mcp: ['release_loop_record_round', 'release_loop_log_step'] },
  { key: 'release-loop-bugs', title: 'Triage and fix bugs (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Runs`, api: ['POST /api/release-loop/runs/:id/bugs', 'POST /api/release-loop/bugs/:id/fix'], mcp: ['release_loop_add_bug', 'release_loop_bug_action'] },
  { key: 'release-loop-reconciliation', title: 'Reconcile a run (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Runs`, api: ['POST /api/release-loop/runs/:id/reconciliation', 'PUT /api/release-loop/runs/:id/reconciliation/:itemId'], mcp: ['release_loop_add_reconciliation', 'release_loop_resolve_reconciliation'] },
  { key: 'release-cut-read', title: 'List releases and read a frozen or open release (admin)', group: 'Release cut', ui: `${WS} > Journeys > Release loop > Releases`, api: ['GET /api/release-cut/releases', 'GET /api/release-cut/releases/:version'], mcp: ['release_cut_list_releases', 'release_cut_get_release'] },
  { key: 'session-plans-read', title: 'List session estimates, read one, and see expected versus actual (admin)', group: 'Release cut', ui: `${WS} > Journeys > Release loop > Session plans`, api: ['GET /api/release-cut/sessions', 'GET /api/release-cut/sessions/report', 'GET /api/release-cut/sessions/:session'], mcp: ['release_cut_list_sessions', 'release_cut_session_report'] },
  { key: 'session-plans-write', title: 'Record an estimate (or re-estimate) and record a merge (admin)', group: 'Release cut', ui: `${WS} > Journeys > Release loop > Session plans`, api: ['POST /api/release-cut/sessions/estimate', 'POST /api/release-cut/sessions/:session/merge'], mcp: ['release_cut_record_estimate', 'release_cut_record_merge'] },
  { key: 'session-plans-close', title: 'Close a session (finalize path: runs the finalization gate) (admin)', group: 'Release cut', ui: `${WS} > Journeys > Release loop > Session plans`, api: ['POST /api/release-cut/sessions/:session/close'], mcp: ['release_cut_close_session'] },
  { key: 'release-loop-escalations', title: 'List escalations (admin)', group: 'Release loop', ui: `${WS} > Journeys > Release loop > Escalations`, api: ['GET /api/release-loop/escalations'], mcp: ['release_loop_list_escalations'] },
  // ── After-session mapping (admin) ─────────────────────────────────────────
  { key: 'session-mapping-config', title: 'Read, save and reset the mapping rules (admin)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['GET /api/session-mapping/config', 'PUT /api/session-mapping/config', 'DELETE /api/session-mapping/config'], mcp: ['session_mapping_config', 'session_mapping_config_save'] },
  { key: 'session-mapping-sessions', title: 'List, read and re-map analysed sessions (admin)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['GET /api/session-mapping/sessions', 'GET /api/session-mapping/sessions/:id', 'POST /api/session-mapping/sessions/:id/remap'], mcp: ['session_mapping_sessions', 'session_mapping_remap'] },
  { key: 'session-mapping-trends', title: 'Read token, spend and time trends (admin)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['GET /api/session-mapping/trends'], mcp: ['session_mapping_trends'] },
  { key: 'session-mapping-proposals', title: 'List, reject and apply mapping proposals (admin; apply runs the finalization gate)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['GET /api/session-mapping/proposals', 'POST /api/session-mapping/proposals/:id/reject', 'POST /api/session-mapping/proposals/:id/apply'], mcp: ['session_mapping_proposals', 'session_mapping_proposal_decide'] },
  { key: 'session-mapping-import', title: 'Import a transcript, metrics JSON or scan the server folder (admin)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['POST /api/session-mapping/import/transcript', 'POST /api/session-mapping/import/metrics', 'POST /api/session-mapping/import/scan'], mcp: ['session_mapping_import'] },
  { key: 'session-mapping-failures', title: 'List and dispose capture failures (admin)', group: 'Session mapping', ui: `${WS} > Journeys > Sessions`, api: ['GET /api/session-mapping/failures', 'PUT /api/session-mapping/failures/:id/disposition'], mcp: ['session_mapping_failures', 'session_mapping_failure_dispose'] },
  // ── Platform agent runner (admin) ─────────────────────────────────────────
  { key: 'agent-runner-overview', title: 'See the worker, queue, proposals waiting and observed usage (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Overview`, api: ['GET /api/agent-runner/overview', 'GET /api/agent-runner/rejected-worker-calls'], mcp: ['agent_runner_overview'] },
  { key: 'agent-runner-settings', title: 'Size limits S/M/L, turn limit, concurrency, model, shared modules (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Settings`, api: ['GET /api/agent-runner/settings', 'PUT /api/agent-runner/settings'], mcp: ['agent_runner_settings'] },
  { key: 'agent-runner-secrets', title: 'GitHub token (stored encrypted) and worker token (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Settings`, api: ['PUT /api/agent-runner/settings/github-token', 'DELETE /api/agent-runner/settings/github-token', 'POST /api/agent-runner/settings/worker-token'], mcp: null, mcpExclusion: 'A secret is never passed through an agent session: tokens are created and rotated on the website only.' },
  { key: 'agent-runner-roster', title: 'The agent roster and each agent\'s versioned prompt (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Agents`, api: ['GET /api/agent-runner/agents', 'GET /api/agent-runner/agents/:key/prompt'], mcp: ['agent_runner_list_agents'] },
  { key: 'agent-runner-runs', title: 'Prompt an agent, watch, stop, requeue and retry its run (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Agents and Runs`, api: ['GET /api/agent-runner/runs', 'POST /api/agent-runner/runs', 'GET /api/agent-runner/runs/:id', 'POST /api/agent-runner/runs/:id/stop', 'POST /api/agent-runner/runs/:id/requeue', 'POST /api/agent-runner/runs/:id/retry'], mcp: ['agent_runner_start_run', 'agent_runner_list_runs', 'agent_runner_get_run', 'agent_runner_run_action'] },
  { key: 'agent-runner-scope', title: 'Approve or decline a scope request from a work-order run (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Runs > (a run) > Scope requests`, api: ['POST /api/agent-runner/runs/:id/scope-requests/:rid/decision'], mcp: ['agent_runner_scope_decision'] },
  { key: 'agent-runner-outputs', title: 'Read and decide what agents produced: draft specs, results, amendment proposals, bugs, plans, enhancement proposals, shaped seeds (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Outputs`, api: ['GET /api/agent-runner/outputs', 'GET /api/agent-runner/outputs/:id', 'POST /api/agent-runner/outputs/:id/decision', 'GET /api/agent-runner/outputs/:id/amendment'], mcp: ['agent_runner_outputs', 'agent_runner_decide_output'] },
  { key: 'agent-runner-test-plan', title: 'Smoke suites, baselines and the smoke-vs-regression test plan (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Test plan`, api: ['GET /api/agent-runner/baselines', 'POST /api/agent-runner/test-plan'], mcp: ['agent_runner_baselines', 'agent_runner_test_plan'] },
  { key: 'agent-runner-seeds', title: 'Backlog seeds: seed, shaped, ready, promoted, with history (admin)', group: 'Agent runner', ui: `${WS} > Journeys > Agent runner > Backlog seeds`, api: ['GET /api/agent-runner/seeds', 'POST /api/agent-runner/seeds', 'GET /api/agent-runner/seeds/:id', 'POST /api/agent-runner/seeds/:id/answer', 'POST /api/agent-runner/seeds/:id/move'], mcp: ['agent_runner_seeds'] },
  { key: 'agent-runner-worker', title: 'Worker protocol: heartbeat, claim, progress, scope request, complete, git credential (worker token)', group: 'Agent runner', ui: null, uiExclusion: 'Machine-to-machine: called by scripts/agent-worker.mjs with a worker token; a person sees its effect on the Overview and Runs screens.', api: ['POST /api/agent-runner/worker/heartbeat', 'POST /api/agent-runner/worker/claim', 'POST /api/agent-runner/worker/runs/:id/events', 'POST /api/agent-runner/worker/runs/:id/scope-request', 'POST /api/agent-runner/worker/runs/:id/complete', 'GET /api/agent-runner/worker/runs/:id/git-credential'], mcp: null, mcpExclusion: 'The worker is a program, not an agent session; its calls need the worker token and run no user-facing action.' },
  { key: 'production-smoke-account', title: 'See the fictional production smoke test account and ready it (create it with a password, or re-ready it); lists the GitHub secret names to add (admin)', group: 'Production smoke', ui: `${WS} > Journeys > Production smoke`, api: ['GET /api/production-smoke/account', 'POST /api/production-smoke/account'], mcp: ['production_smoke_account_status', 'production_smoke_account_ready'] },
  // ── Release tracker ───────────────────────────────────────────────────────
  // Live release tracker (docs/changes/live-release-tracker.md, release-scope.md)
  { key: 'release-tracker-state', title: 'Read the release tracker (features with planned / backlog / added scope)', group: 'Release tracker', ui: `${WS} > Release tracker`, api: ['GET /api/release-tracker/access', 'GET /api/release-tracker/state'], mcp: ['release_tracker_get_state'] },
  { key: 'release-tracker-stream', title: 'Live updates and shared read-only link', group: 'Release tracker', ui: `${WS} > Release tracker`, api: ['GET /api/release-tracker/stream', 'GET /api/release-tracker/shared/:token/state', 'GET /api/release-tracker/shared/:token/stream'], mcp: null, mcpExclusion: 'Server-sent event stream and public share-link view for people; an agent reads the same data with release_tracker_get_state.' },
  { key: 'release-tracker-admin', title: 'Ingest, pull, settings, tokens and logs (admin)', group: 'Release tracker', ui: `${WS} > Release tracker > Settings`, api: ['POST /api/release-tracker/snapshots', 'POST /api/release-tracker/pull', 'GET /api/release-tracker/settings', 'PUT /api/release-tracker/settings', 'POST /api/release-tracker/settings/webhook-secret', 'GET /api/release-tracker/tokens', 'POST /api/release-tracker/tokens', 'DELETE /api/release-tracker/tokens/:id', 'GET /api/release-tracker/snapshots', 'GET /api/release-tracker/ingest-log'], mcp: ['release_tracker_ingest_snapshot', 'release_tracker_list_snapshots', 'release_tracker_pull_now', 'release_tracker_get_settings', 'release_tracker_save_settings', 'release_tracker_create_token', 'release_tracker_revoke_token', 'release_tracker_list_ingest_log', 'release_tracker_webhook_secret'], mcpExclusion: 'Push ingest by bearer ingest token is for the repository workflow; an agent stores snapshots with release_tracker_ingest_snapshot as an administrator.' },
  { key: 'release-tracker-read', title: 'Read release records (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['GET /api/release-intelligence/releases', 'GET /api/release-intelligence/releases/:id'], mcp: ['release_tracker_read'] },
  { key: 'release-create', title: 'Create a release record (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['POST /api/release-intelligence/releases'], mcp: ['release_create'] },
  { key: 'release-feature-add', title: 'Add a feature to a release (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['POST /api/release-intelligence/releases/:id/features'], mcp: ['release_feature_add'] },
  { key: 'release-approve', title: 'Approve or reopen a release (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['POST /api/release-intelligence/releases/:id/approve', 'POST /api/release-intelligence/releases/:id/reopen'], mcp: ['release_approve', 'release_reopen'] },
  { key: 'release-failed-runs', title: 'List, record and dispose failed runs (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['GET /api/release-intelligence/failed-runs', 'POST /api/release-intelligence/failed-runs', 'PUT /api/release-intelligence/failed-runs/:id/disposition'], mcp: ['release_failed_runs_list', 'release_failed_run_record', 'release_failed_run_dispose'] },
  { key: 'release-outputs', title: 'List outputs and link them to releases (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['GET /api/release-intelligence/outputs', 'PUT /api/release-intelligence/outputs/:id/release'], mcp: ['release_outputs_list', 'release_output_link'] },
  { key: 'release-trends', title: 'Read contribution trends (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['GET /api/release-intelligence/trends'], mcp: ['release_trends_read'] },
  { key: 'release-import', title: 'Import release documents, snapshots and repository logs (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['POST /api/release-intelligence/import/document', 'POST /api/release-intelligence/import/snapshot', 'POST /api/release-intelligence/import/repository'], mcp: ['release_import_document', 'release_import_snapshot', 'release_import_repository'] },
  { key: 'release-config', title: 'Read, save and reset the tracker rules (admin)', group: 'Release tracker', ui: `${WS} > Journeys > Release Intelligence`, api: ['GET /api/release-intelligence/config', 'PUT /api/release-intelligence/config', 'DELETE /api/release-intelligence/config'], mcp: ['release_config_read', 'release_config_save', 'release_config_reset'] },

  // ── Render bindings ───────────────────────────────────────────────────────
  { key: 'render-bindings-view', title: 'Open a rendering, an item and its Data map; read history', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Renderings`, api: [`GET ${RBA}/renderings`, `GET ${RBA}/renderings/:key`, `GET ${RBA}/renderings/:key/subjects/:subjectKey`, `GET ${RBA}/renderings/:key/subjects/:subjectKey/history`, `GET ${RBA}/stream`], mcp: ['render_binding_renderings_list', 'render_binding_rendering_read', 'render_binding_item_read', 'render_binding_item_history'] },
  { key: 'render-bindings-board-item', title: 'Add a workshop board item', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Renderings > Workshop board > Add item`, api: [`POST ${RBA}/renderings/:key/subjects`], mcp: ['render_binding_board_item_add'] },
  { key: 'render-bindings-change', title: 'Change a mapped value (live, or proposed for approval)', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Renderings > (item) > Change a value`, api: [`POST ${RBA}/changes`], mcp: ['render_binding_change_submit'] },
  { key: 'render-bindings-pending', title: 'Pending changes queue and impact analysis', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Pending changes`, api: [`GET ${RBA}/changes/pending`, `GET ${RBA}/changes/:id/impact`], mcp: ['render_binding_pending_list', 'render_binding_change_impact'] },
  { key: 'render-bindings-decide', title: 'Approve or reject a pending change (admin)', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Pending changes > Approve / Reject`, api: [`POST ${RBA}/changes/:id/approve`, `POST ${RBA}/changes/:id/reject`], mcp: ['render_binding_change_decide'] },
  { key: 'render-bindings-settings', title: 'Binding policy, field editable roles and approval steps (admin)', group: 'Render bindings', ui: `${WS} > Journeys > Render Bindings > Settings`, api: [`GET ${RBA}/settings`, `PUT ${RBA}/settings/bindings`, `DELETE ${RBA}/settings/bindings`, `PUT ${RBA}/settings/fields/:portKey/:objectKey/:fieldKey`, `PUT ${RBA}/settings/steps/:id`], mcp: ['render_binding_settings_read', 'render_binding_settings_save'] },

  // ── Journey flow studio ───────────────────────────────────────────────────
  { key: 'flow-studio-flows', title: 'List, create, open, save and archive flows', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > Flows`, api: [`GET ${FSA}/flows`, `POST ${FSA}/flows`, `GET ${FSA}/flows/:id`, `PUT ${FSA}/flows/:id`, `DELETE ${FSA}/flows/:id`], mcp: ['flow_studio_flows_list', 'flow_studio_flow_create', 'flow_studio_flow_read', 'flow_studio_flow_save'] },
  { key: 'flow-studio-validate-history', title: 'Validate a flow, read history, restore a version', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > (flow) > Check / History`, api: [`POST ${FSA}/flows/:id/validate`, `GET ${FSA}/flows/:id/history`, `POST ${FSA}/flows/:id/restore`], mcp: ['flow_studio_flow_validate', 'flow_studio_flow_history', 'flow_studio_flow_restore'] },
  { key: 'flow-studio-publish', title: 'Preview the impact and publish a flow', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > (flow) > Publish`, api: [`GET ${FSA}/flows/:id/publish-preview`, `POST ${FSA}/flows/:id/publish`], mcp: ['flow_studio_publish_preview', 'flow_studio_flow_publish'] },
  { key: 'flow-studio-export-import', title: 'Export a flow or template (JSON, HTML viewer, journey definition) and import JSON', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > (flow) > Export / Flows > Import`, api: [`GET ${FSA}/flows/:id/export`, `GET ${FSA}/templates/:id/export`, `GET ${FSA}/templates/seed/:key/export`, `POST ${FSA}/flows/import`], mcp: ['flow_studio_flow_export', 'flow_studio_flow_import'] },
  { key: 'flow-studio-templates', title: 'Save a flow as a template; overwrite or delete a template with impact', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > Templates`, api: [`POST ${FSA}/flows/:id/save-as-template`, `GET ${FSA}/templates/:id/impact`, `PUT ${FSA}/templates/:id`, `DELETE ${FSA}/templates/:id`], mcp: ['flow_studio_template_save', 'flow_studio_template_change'] },
  { key: 'flow-studio-agent-draft', title: 'Ask the studio agent to draft step or connector metadata', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > (flow) > Draft with agent`, api: [`POST ${FSA}/flows/:id/agent-draft`], mcp: ['flow_studio_agent_draft'] },
  { key: 'flow-studio-definition', title: 'Studio definition: shapes, colours, fields, rules and access (Settings)', group: 'Journey flow studio', ui: `${WS} > Journeys > Journey Flow Studio > Settings`, api: [`GET ${FSA}/definition`, `PUT ${FSA}/definition`, `DELETE ${FSA}/definition`], mcp: ['flow_studio_definition_read', 'flow_studio_definition_save'] },

  // ── Platform access (this feature) ────────────────────────────────────────
  { key: 'access-tokens', title: 'Create, list and revoke access tokens', group: 'Platform access', ui: `${WS} > Journeys > Connected Agents`, api: ['GET /api/platform/tokens', 'POST /api/platform/tokens', 'DELETE /api/platform/tokens/:id'], mcp: null, mcpExclusion: 'Credentials are managed by a signed-in person in the website; a token can never mint or revoke tokens.' },
  { key: 'mcp-connection-info', title: 'Show the MCP address and the tools a token gets', group: 'Platform access', ui: `${WS} > Journeys > Connected Agents`, api: ['GET /api/platform/mcp'], mcp: ['platform_mcp_info'] },
  { key: 'capabilities-map', title: 'Show this parity map (admin)', group: 'Platform access', ui: `${WS} > Journeys > Capabilities`, api: ['GET /api/platform/capabilities'], mcp: ['platform_capabilities_map'] },
  { key: 'data-model-map-view', title: 'Open the data model map: domains, tables, search, one table with its columns, relations and routes', group: 'Data model map', ui: `${WS} > Data model map (datamodel.read permission; administrators by default)`, api: [`GET ${DMA}/catalog`, `GET ${DMA}/search`, `GET ${DMA}/tables/:name`, `GET ${DMA}/code`], mcp: ['data_model_catalog_read', 'data_model_search', 'data_model_table_read', 'data_model_code_read'] },
  { key: 'data-model-map-picker', title: 'Data-object and field picker source for flow builders', group: 'Data model map', ui: `${WS} > Data model map > (a table) > Use as a data object`, api: [`GET ${DMA}/picker`], mcp: ['data_model_picker'] },
  { key: 'data-model-map-rules', title: 'Edit the domain grouping rules (datamodel.write permission)', group: 'Data model map', ui: `${WS} > Data model map > Settings`, api: [`GET ${DMA}/rules`, `PUT ${DMA}/rules`, `DELETE ${DMA}/rules`], mcp: ['data_model_rules_read', 'data_model_rules_save'] },
]);

/** Computes per-capability status (the Capabilities screen and the check script share this). */
export function evaluateCapabilities(capabilities = CAPABILITIES, toolNames = MCP_TOOL_NAMES) {
  return capabilities.map((c) => {
    const missingTools = (c.mcp || []).filter((n) => !toolNames.includes(n));
    const ui = c.ui ? 'yes' : c.uiExclusion ? 'excluded' : 'gap';
    const api = c.api?.length ? 'yes' : 'gap';
    const mcp = c.mcp?.length && !missingTools.length ? 'yes' : c.mcpExclusion ? 'excluded' : 'gap';
    return {
      key: c.key, title: c.title, group: c.group,
      ui: c.ui || null, api: c.api || [], mcp: c.mcp || [],
      uiStatus: ui, apiStatus: api, mcpStatus: mcp,
      uiExclusion: c.uiExclusion || null, mcpExclusion: c.mcpExclusion || null,
      gap: c.gap || null, missingTools,
      full: ui !== 'gap' && api !== 'gap' && mcp !== 'gap',
    };
  });
}

export function summarizeCapabilities(rows) {
  return {
    total: rows.length,
    full: rows.filter((r) => r.full).length,
    uiGaps: rows.filter((r) => r.uiStatus === 'gap').length,
    mcpGaps: rows.filter((r) => r.mcpStatus === 'gap').length,
    apiGaps: rows.filter((r) => r.apiStatus === 'gap').length,
  };
}
